### ISSUE TITLE
Follow SPEC-0 for minimum supported versions of dependencies

### ISSUE THREAD

**Issue by ivirshup** [chanzuckerberg/cellxgene-census#1177]
## Motivation

https://scientific-python.org/specs/spec-0000/

It would be nice to have a clear policy on what the support window for dependencies are. This makes it clear when we can use newer features, and when we can stop supporting old versions of libraries.

As an illustration of why this is important, let's say a user comes across a bug specific to python 3.8. It could turnout that this is a bug in all the versions of pandas that support 3.8, but was fixed after pandas dropped support for 3.8. Now it's basically on us to solve bugs in dependencies since we have a larger support window that our dependencies do.

## Definition of Done

Bump minimum versions of dependencies and change policies around this going forward.

## Tasks

- [ ] Make sure no important downstream tasks are depending on an old version of a dep (there may be some tiledb thing around python 3.8?)
- [ ] Bump the minimum versions
- [ ] Remove CI/ CD infra that is specific to old versions
