### ISSUE TITLE
Stop blocking Boroni collection

### ISSUE THREAD

**Issue by ivirshup** [chanzuckerberg/cellxgene-census#1263]
Once the data problems are resolved we should stop blocking this dataset:

Tracking issue on data portal:

* https://github.com/chanzuckerberg/single-cell-curation/issues/981
 
Dataset blocked in:

* https://github.com/chanzuckerberg/cellxgene-census/pull/1262

## TODOs

- [x] Check if it is in LTS
  ~- [x] If it is, publish errata~
- [x] Add dataset to blocklist @ivirshup 
- [ ] Remove dataset from blocklist

**Comment by brianraymor** [comment]
@ivirshup - The curation issue was resolved. This is ready for action.
