### ISSUE TITLE
Create a requirements.txt for notebooks

### ISSUE THREAD

**Issue by atolopko-czi** [chanzuckerberg/cellxgene-census#240]
## Motivation

* Notebook virtualenv is easier to setup
* README instructions do not need to be updated if/when package reqs change.

## Definition of Done
- [x] New api/python/notebooks/requirements.txt file contains all necessary Python pkgs for notebooks (now listed in api/python/notebooks/README.md)
- [x] api/python/notebooks/README.md updated to reference requirements.txt and not explicit packages
- [x] Cell Census Manual Build instructions (GDoc) updated to reference requirements.txt and not explicit packages

## Tasks

Obvious per DoD, above

**Comment by atolopko-czi** [comment]
All tasks now done, closing!
