### ISSUE TITLE
Update builder to use /datasets index endpoint

### ISSUE THREAD

**Issue by atolopko-czi** [chanzuckerberg/cellxgene-census#332]
## Motivation

Simplifies code and should improve reliability of the builder process (see #311), due to fewer API requests being made. A single API failure currently fails the entire build process.

## Definition of Done

The builder calls /datasets/index a single time to retrieve all datasets, rather than 3 separate endpoints for collections, datasets, and assets.

This issue does _not_ need to retrieve and store the `dataset_version_id`, which is newly available. This follow-up work can be handled by https://github.com/chanzuckerberg/cell-census/issues/6, which will require a Census schema update.

## Tasks

- [ ] Update `cell_census_builder.build_soma.manifest.load_manifest_from_CxG()` to use just `/datasets/index`.
- [ ] Consider implementing #311 at the same time.
- [ ] Perform a full test build.

## Considerations

Implementing this sooner than later and testing against the endpoint, which is [now in the dev env](https://github.com/chanzuckerberg/single-cell-data-portal/issues/4324#issuecomment-1491135698), will ensure that any problems with the new endpoint can be addressed before it is deployed to prod.

**Comment by atolopko-czi** [comment]
@danieljhegeman The /datasets endpoint doesn't return an explicit S3 URI or filesize per https://api.cellxgene.dev.single-cell.czi.technology/curation/ui/#/dataset/backend.curation.api.v1.curation.datasets.actions.get. Thought I saw these in designs--is it in progress or not planned?

**Comment by danieljhegeman** [comment]
@atolopko-czi the explicit s3 uri will be added in the next day or two, once we apply the bucket changes and merge the PR which should happen today. Ideally all is in by tomorrow's staging deploy. Then the `.assets[]` array on each dataset object will include file type, size, and s3 uri.
