### ISSUE TITLE
Update python notebooks to comply with notebook editorial guidelines

### ISSUE THREAD

**Issue by pablo-gar** [chanzuckerberg/cellxgene-census#360]
## Motivation

We have editorial guidelines that notebooks have to follow

https://github.com/chanzuckerberg/cellxgene-census/blob/main/docs/cell_census_notebook_guidelines.md

## Definition of Done

Update all python notebooks to adhere to guidelines 

## Tasks
- [x] [comp_bio_census_info.ipynb](https://github.com/chanzuckerberg/cellxgene-census/blob/main/api/python/notebooks/analysis_demo/comp_bio_census_info.ipynb)
- [x] [comp_bio_data_integration_scvi.ipynb](https://github.com/chanzuckerberg/cellxgene-census/blob/main/api/python/notebooks/analysis_demo/comp_bio_data_integration_scvi.ipynb)
- [x] [comp_bio_explore_and_load_lung_data.ipynb](https://github.com/chanzuckerberg/cellxgene-census/blob/main/api/python/notebooks/analysis_demo/comp_bio_explore_and_load_lung_data.ipynb)
- [x] [comp_bio_normalizing_full_gene_sequencing.ipynb](https://github.com/chanzuckerberg/cellxgene-census/blob/main/api/python/notebooks/analysis_demo/comp_bio_normalizing_full_gene_sequencing.ipynb)
- [x] [comp_bio_query_data_and_metadata.ipynb](https://github.com/chanzuckerberg/cellxgene-census/blob/main/api/python/notebooks/analysis_demo/comp_bio_query_data_and_metadata.ipynb)
- [x] [census_axis_query.ipynb](https://github.com/chanzuckerberg/cellxgene-census/blob/main/api/python/notebooks/api_demo/census_axis_query.ipynb)
- [x] [census_compute_over_X.ipynb](https://github.com/chanzuckerberg/cellxgene-census/blob/main/api/python/notebooks/api_demo/census_compute_over_X.ipynb)
- [x] [census_dataset_presence.ipynb](https://github.com/chanzuckerberg/cellxgene-census/blob/main/api/python/notebooks/api_demo/census_dataset_presence.ipynb)
- [x] [census_datasets.ipynb](https://github.com/chanzuckerberg/cellxgene-census/blob/main/api/python/notebooks/api_demo/census_datasets.ipynb)
- [x] [census_query_extract.ipynb](https://github.com/chanzuckerberg/cellxgene-census/blob/main/api/python/notebooks/api_demo/census_query_extract.ipynb)
- [x] [census_rank_gene_groups.ipynb](https://github.com/chanzuckerberg/cellxgene-census/blob/main/api/python/notebooks/api_demo/census_rank_gene_groups.ipynb)
- [x] [census_summary_cell_counts.ipynb](https://github.com/chanzuckerberg/cellxgene-census/blob/main/api/python/notebooks/api_demo/census_summary_cell_counts.ipynb)

**Comment by pablo-gar** [comment]
Completed #377
