### ISSUE TITLE
Make census builder adhere to census schema 1.0

### ISSUE THREAD

**Issue by pablo-gar** [chanzuckerberg/cellxgene-census#390]
## Description

To adhere with Census Schema version 1.0

## Tasks

In `census["census_info"]["summary"]`:

- [ ] Update value in column `label` from `"cell_census_build_date"` to `"census_build_date"`.
- [ ] Update value in column `label` from `"cell_census_schema_version"` to `"census_schema_version"` and update `value` to `"1.0.0"`
- [ ] Add  value in column `label`  `"dataset_schema_version"` and `value` `"3.0.0"`
