### ISSUE TITLE
Create an Articles section in the doc-site

### ISSUE THREAD

**Issue by pablo-gar** [chanzuckerberg/cellxgene-census#527]
## Description

This section can include:

- News
   - API
   - Schema updates
   - Data release updates
- Mini-analysis that serve as demonstrations and learnings:
    - e.g. SCVI out-of-the-box
    - Training workflow with results using pytroch loaders.

## Tasks

- [x] Create editorial guidelines
- [x] Create folder in `./docs` to host md files and link to doc-site. Perform any necessary changes to doc-site building pipeline
- [x] Add "hello world" article

**Comment by pablo-gar** [comment]
Completed #671
