### ISSUE TITLE
Add colab link to tutorials with low computing requirements

### ISSUE THREAD

**Issue by pablo-gar** [chanzuckerberg/cellxgene-census#529]
## Description

To increase access to Census usage all tutorials that have low compute requirements should have a google colab equivalent, similar to this notebook 

![image](https://github.com/chanzuckerberg/cellxgene-census/assets/29237819/0a58ed86-a5a3-4080-9cc0-9af67c53a7b4)

## Tasks

- [ ] Modify the notebook editorial guidelines to provide guidance on the text and link to be added.
- [ ] Scan existing notebooks and create a candidate list to those that can have a google colab equivalent (i.e. low computing requirements).
- [ ] Update such notebooks.

**Comment by Ivana-Jelic** [comment]
Another example that we've been using for onboarding for months and has been a great way to get users started using cell census API quickly: https://colab.research.google.com/drive/1wJjN2pUXQw_UAVmn4d4O7oBFK-7DOFLw?usp=sharing 
(Intro demo)
