### ISSUE TITLE
add enumerated/categorical support

### ISSUE THREAD

**Issue by bkmartinjr** [chanzuckerberg/cellxgene-census#604]
tiledbsoma is working on the addition of native support for categorical/enumerated types, a la' pandas.Categorical.

When this work lands, the Census obs/var dataframes need to incorporate it for all label columns that are repetiive (e.g., assay_ontology_term_id, etc), as there should be a significant performance improvement, as well as a usability improvement (will materialize into Categoricals or Factors)

**Comment by pablo-gar** [comment]
PR on TileDB-SOMA https://github.com/single-cell-data/TileDB-SOMA/pull/1511

**Comment by bkmartinjr** [comment]
Currently blcoked by single-cell-data/TileDB-SOMA#1973

**Comment by bkmartinjr** [comment]
PR #896 adds enum support, but disabled by a feature flag until issues upstream are resolved.  Toggling the feature flag is currently waiting on:

- [ ] single-cell-data/TileDB-SOMA#1988
- [ ] TileDB-Inc/TileDB-Py#1880
- [ ] TileDB-Inc/TileDB-Py#1879

**Comment by bkmartinjr** [comment]
Latest update: blocked by filter query fix which is slated for TileDB core 2.21 at the earliest.
